import type { IconType } from "react-icons";
import {
  SiPython,
  SiJavascript,
  SiTypescript,
  SiOpenjdk,
  SiC,
  SiCplusplus,
  SiKotlin,
  SiOcaml,
  SiMysql,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiFlask,
  SiSpring,
  SiPostgresql,
  SiMongodb,
  SiFirebase,
  SiGit,
  SiGithub,
  SiTailwindcss,
  SiDocker,
  SiVercel,
} from "react-icons/si";
import { TbApi } from "react-icons/tb";
import { FaInfinity } from "react-icons/fa6";

export const skillIcons: Record<string, { Icon: IconType; color: string }> = {
  Python: { Icon: SiPython, color: "#3776AB" },
  JavaScript: { Icon: SiJavascript, color: "#F7DF1E" },
  TypeScript: { Icon: SiTypescript, color: "#3178C6" },
  Java: { Icon: SiOpenjdk, color: "#EA2D2E" },
  C: { Icon: SiC, color: "#A8B9CC" },
  "C++": { Icon: SiCplusplus, color: "#00599C" },
  Kotlin: { Icon: SiKotlin, color: "#7F52FF" },
  OCaml: { Icon: SiOcaml, color: "#EC6813" },
  SQL: { Icon: SiMysql, color: "#4479A1" },
  "React.js": { Icon: SiReact, color: "#61DAFB" },
  "Next.js": { Icon: SiNextdotjs, color: "currentColor" },
  "Node.js": { Icon: SiNodedotjs, color: "#5FA04E" },
  "Express.js": { Icon: SiExpress, color: "currentColor" },
  Flask: { Icon: SiFlask, color: "currentColor" },
  "Spring Boot": { Icon: SiSpring, color: "#6DB33F" },
  PostgreSQL: { Icon: SiPostgresql, color: "#4169E1" },
  MongoDB: { Icon: SiMongodb, color: "#47A248" },
  MySQL: { Icon: SiMysql, color: "#4479A1" },
  Firebase: { Icon: SiFirebase, color: "#FFCA28" },
  "REST API design": { Icon: TbApi, color: "#8b909c" },
  Git: { Icon: SiGit, color: "#F05032" },
  GitHub: { Icon: SiGithub, color: "currentColor" },
  "CI/CD": { Icon: FaInfinity, color: "#8b909c" },
  "Tailwind CSS": { Icon: SiTailwindcss, color: "#38BDF8" },
  Docker: { Icon: SiDocker, color: "#2496ED" },
  Vercel: { Icon: SiVercel, color: "currentColor" },
};
